library verilog;
use verilog.vl_types.all;
entity scheduler2_free_search_64to2 is
    port(
        iENTRY0_VALID   : in     vl_logic;
        iENTRY1_VALID   : in     vl_logic;
        iENTRY2_VALID   : in     vl_logic;
        iENTRY3_VALID   : in     vl_logic;
        iENTRY4_VALID   : in     vl_logic;
        iENTRY5_VALID   : in     vl_logic;
        iENTRY6_VALID   : in     vl_logic;
        iENTRY7_VALID   : in     vl_logic;
        iENTRY8_VALID   : in     vl_logic;
        iENTRY9_VALID   : in     vl_logic;
        iENTRY10_VALID  : in     vl_logic;
        iENTRY11_VALID  : in     vl_logic;
        iENTRY12_VALID  : in     vl_logic;
        iENTRY13_VALID  : in     vl_logic;
        iENTRY14_VALID  : in     vl_logic;
        iENTRY15_VALID  : in     vl_logic;
        iENTRY16_VALID  : in     vl_logic;
        iENTRY17_VALID  : in     vl_logic;
        iENTRY18_VALID  : in     vl_logic;
        iENTRY19_VALID  : in     vl_logic;
        iENTRY20_VALID  : in     vl_logic;
        iENTRY21_VALID  : in     vl_logic;
        iENTRY22_VALID  : in     vl_logic;
        iENTRY23_VALID  : in     vl_logic;
        iENTRY24_VALID  : in     vl_logic;
        iENTRY25_VALID  : in     vl_logic;
        iENTRY26_VALID  : in     vl_logic;
        iENTRY27_VALID  : in     vl_logic;
        iENTRY28_VALID  : in     vl_logic;
        iENTRY29_VALID  : in     vl_logic;
        iENTRY30_VALID  : in     vl_logic;
        iENTRY31_VALID  : in     vl_logic;
        iENTRY32_VALID  : in     vl_logic;
        iENTRY33_VALID  : in     vl_logic;
        iENTRY34_VALID  : in     vl_logic;
        iENTRY35_VALID  : in     vl_logic;
        iENTRY36_VALID  : in     vl_logic;
        iENTRY37_VALID  : in     vl_logic;
        iENTRY38_VALID  : in     vl_logic;
        iENTRY39_VALID  : in     vl_logic;
        iENTRY40_VALID  : in     vl_logic;
        iENTRY41_VALID  : in     vl_logic;
        iENTRY42_VALID  : in     vl_logic;
        iENTRY43_VALID  : in     vl_logic;
        iENTRY44_VALID  : in     vl_logic;
        iENTRY45_VALID  : in     vl_logic;
        iENTRY46_VALID  : in     vl_logic;
        iENTRY47_VALID  : in     vl_logic;
        iENTRY48_VALID  : in     vl_logic;
        iENTRY49_VALID  : in     vl_logic;
        iENTRY50_VALID  : in     vl_logic;
        iENTRY51_VALID  : in     vl_logic;
        iENTRY52_VALID  : in     vl_logic;
        iENTRY53_VALID  : in     vl_logic;
        iENTRY54_VALID  : in     vl_logic;
        iENTRY55_VALID  : in     vl_logic;
        iENTRY56_VALID  : in     vl_logic;
        iENTRY57_VALID  : in     vl_logic;
        iENTRY58_VALID  : in     vl_logic;
        iENTRY59_VALID  : in     vl_logic;
        iENTRY60_VALID  : in     vl_logic;
        iENTRY61_VALID  : in     vl_logic;
        iENTRY62_VALID  : in     vl_logic;
        iENTRY63_VALID  : in     vl_logic;
        oSELECT0_VALID  : out    vl_logic;
        oSELECT0_ENTRY  : out    vl_logic_vector(5 downto 0);
        oSELECT1_VALID  : out    vl_logic;
        oSELECT1_ENTRY  : out    vl_logic_vector(5 downto 0)
    );
end scheduler2_free_search_64to2;
