

task task_disp_logic_register_all;
	begin
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_VALID)begin
			$display("[INFO]Time : %d, Core(EX1) Register Writeback : Reg[%d(demical)] = %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_LOGIC_DEST, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_DATA);
		end
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_VALID)begin
			$display("[INFO]Time : %d, Core(EX2) Register Writeback : Reg[%d(demical)] = %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_LOGIC_DEST, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_DATA);
		end
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_VALID)begin
			$display("[INFO]Time : %d, Core(EX3) Register Writeback : Reg[%d(demical)] = %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_LOGIC_DEST, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_DATA);
		end
	end
endtask


task task_disp_logic_register_single;
	input [4:0] task_logic_register;
	begin
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_VALID && TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_LOGIC_DEST == task_logic_register)begin
			$display("[INFO]Time : %d, Core(EX1) Register Writeback : Reg[%d(demical)] = %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_LOGIC_DEST, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT1.oSCHE2_EX_ALU1_DATA);
		end
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_VALID && TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_LOGIC_DEST == task_logic_register)begin
			$display("[INFO]Time : %d, Core(EX2) Register Writeback : Reg[%d(demical)] = %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_LOGIC_DEST, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT2.oSCHE2_EX_ALU2_DATA);
		end
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_VALID && TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_LOGIC_DEST == task_logic_register)begin
			$display("[INFO]Time : %d, Core(EX3) Register Writeback : Reg[%d(demical)] = %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_LOGIC_DEST, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_DATA);
		end
	end
endtask
