

task task_disp_loadstore;
	begin
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.iDATAIO_REQ && !TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.b_ldst_pipe_rw)begin
			$display("[INFO]Time : %d, Core(EX3) Load/Store[L], %x, %x, %x, %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.b_ldst_pipe_pcr-32'h4, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.spr_data_info, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oDATAIO_ADDR, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oSCHE2_ALU3_DATA);
		end
		if(TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oDATAIO_REQ && TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.b_ldst_pipe_rw)begin
			$display("[INFO]Time : %d, Core(EX3) Load/Store[S], %x, %x, %x, %x", $time, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.b_ldst_pipe_pcr-32'h4, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.spr_data_info, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oDATAIO_ADDR, TARGET.CORE_IF.CORE_PIPELINE.SATGE7_EX_PORT3.oDATAIO_DATA);
		end
	end
endtask
